export enum Activity {
  DEVELOPMENT = 'DEVELOPMENT',
  TESTING_TU = 'TESTING_TU',
  PASSAGE_TH = 'PASSAGE_TH',
  HOMOLOGATION = 'HOMOLOGATION',
  ADMINISTRATIVE_TASKS = 'ADMINISTRATIVE_TASKS',
  PRE_SWAP = 'PRE_SWAP',
  SWAP = 'SWAP'
}